### ISSUE TITLE
No support for Custom Gedcom-Tags

### ISSUE THREAD

**Issue by XojoGermany** [d5dhatch/gedcom-grammar#2]
Custom Gedcom-Tags are defined by an underscore followed by Tag (Sample: _RUFNAME or _AKAN). Would be nice, if you can support this ;)

Thanks

**Comment by d5dhatch** [comment]
Ah! Yes! I will look!

**Comment by d5dhatch** [comment]
@neu1886 Any chance you can take a look?  The regex I use to get the tags is the following monstrosity below. I took me a long time to even get that far :)

`patterns: [
	{
		match: "((^0)\\s+|(^1)\\s+|(^2)\\s+|(^3)\\s+|(^4)\\s+|(^5)\\s+)(((@\\S+@)(\\s(.{4})))|((((.{4})(\\s(@\\S+@))))|(((.{4})(.+))))|((.{4})))";
		captures:
			"2":
				name: "ged.level.level0.gedcom"
			"3":
				name: "ged.level.level1.gedcom"
			"4":
				name: "ged.level.level2.gedcom"
			"5":
				name: "ged.level.level3.gedcom"
			"6":
				name: "ged.level.level4.gedcom"
			"7":
				name: "ged.level.level5.gedcom"
			"10":
				name: "ged.xrefID.gedcom"
			"12":
				name: "ged.type.gedcom"
			"16":
				name: "ged.type.gedcom"
			"18":
				name: "ged.xrefID.gedcom"
			"21":
				name: "ged.type.gedcom"	
			"22":
				name: "ged.description.gedcom"
			"23":
				name: "ged.type.gedcom"
	}
]`

**Comment by XojoGermany** [comment]
This RegEx Pattern will parse a Gedcom-Line
`^(0|[1-9]+[0-9]*) (@[^@]+@ |)([A-Za-z0-9_]+)( [^\n\r]*|)$`

You will get
- Level
- Reference (optional)
- Tag
- Value

**Comment by d5dhatch** [comment]
Great! Much better than mine! I can tweak to capture individual levels. One question: for things like
2 SOUR **@S605@** the reference gets captured as part of group 4 which is also used for the long strings of text like 1 NAME **Marjorie Edna /Footitt/**
How might you capture that reference separately?

**Comment by d5dhatch** [comment]
@neu1886 I've taken your string and put here: https://regex101.com/r/Y17Z72/3
If you like go ahead and mess around with it... thanks again your formulation is vastly superior so I'd love the help.

**Comment by d5dhatch** [comment]
OK so @neu1886 I figured it out. Thanks so much. I will post a fix shortly.

**Comment by d5dhatch** [comment]
Fixed!
