### ISSUE TITLE
Incomplete Syntax for NoteStructure/NoteRecord

### ISSUE THREAD

**Issue by XojoGermany** [d5dhatch/gedcom-grammar#3]
`0 @N1@ NOTE Lorem ipsum dolor sit amet,`
Lorem Ipsum after NOTE-Tag will not highlighted!

**Comment by d5dhatch** [comment]
Thanks for taking a look! I will look into it. I must say my maintenance of this code will be shoddy at best. I am but a mere hack... learning as I go...

**Comment by d5dhatch** [comment]
Fixed!
